<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\..\configureawait.props" />
	<Import Project="..\..\..\..\common.props" />

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1;net8.0;net9.0;net10.0</TargetFrameworks>
		<AssemblyName>LINGYUN.Abp.Dingtalk</AssemblyName>
		<PackageId>LINGYUN.Abp.Dingtalk</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<Description>钉钉基础框架</Description>
		<Nullable>enable</Nullable>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<None Remove="LINGYUN\Abp\Dingtalk\Localization\Resources\*.json" />
		<EmbeddedResource Include="LINGYUN\Abp\Dingtalk\Localization\Resources\*.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AlibabaCloud.SDK.Dingtalk" />
		<PackageReference Include="Volo.Abp.Caching" />
		<PackageReference Include="Volo.Abp.Features" />
		<PackageReference Include="Volo.Abp.Localization" />
		<PackageReference Include="Volo.Abp.Json" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\common\LINGYUN.Abp.Features.LimitValidation\LINGYUN.Abp.Features.LimitValidation.csproj" />
		<ProjectReference Include="..\..\settings\LINGYUN.Abp.Settings\LINGYUN.Abp.Settings.csproj" />
	</ItemGroup>

</Project>
