// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using LINGYUN.Abp.Identity;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace LINGYUN.Abp.Identity;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IIdentityUserAppService), typeof(IdentityUserClientProxy))]
public partial class IdentityUserClientProxy : ClientProxyBase<IIdentityUserAppService>, IIdentityUserAppService
{
    public virtual async Task<ListResultDto<OrganizationUnitDto>> GetOrganizationUnitsAsync(Guid id)
    {
        return await RequestAsync<ListResultDto<OrganizationUnitDto>>(nameof(GetOrganizationUnitsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task SetOrganizationUnitsAsync(Guid id, IdentityUserOrganizationUnitUpdateDto input)
    {
        await RequestAsync(nameof(SetOrganizationUnitsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(IdentityUserOrganizationUnitUpdateDto), input }
        });
    }

    public virtual async Task RemoveOrganizationUnitsAsync(Guid id, Guid ouId)
    {
        await RequestAsync(nameof(RemoveOrganizationUnitsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(Guid), ouId }
        });
    }

    public virtual async Task<ListResultDto<IdentityClaimDto>> GetClaimsAsync(Guid id)
    {
        return await RequestAsync<ListResultDto<IdentityClaimDto>>(nameof(GetClaimsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task AddClaimAsync(Guid id, IdentityUserClaimCreateDto input)
    {
        await RequestAsync(nameof(AddClaimAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(IdentityUserClaimCreateDto), input }
        });
    }

    public virtual async Task UpdateClaimAsync(Guid id, IdentityUserClaimUpdateDto input)
    {
        await RequestAsync(nameof(UpdateClaimAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(IdentityUserClaimUpdateDto), input }
        });
    }

    public virtual async Task DeleteClaimAsync(Guid id, IdentityUserClaimDeleteDto input)
    {
        await RequestAsync(nameof(DeleteClaimAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(IdentityUserClaimDeleteDto), input }
        });
    }

    public virtual async Task ChangePasswordAsync(Guid id, IdentityUserSetPasswordInput input)
    {
        await RequestAsync(nameof(ChangePasswordAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(IdentityUserSetPasswordInput), input }
        });
    }

    public virtual async Task ChangeTwoFactorEnabledAsync(Guid id, TwoFactorEnabledDto input)
    {
        await RequestAsync(nameof(ChangeTwoFactorEnabledAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(TwoFactorEnabledDto), input }
        });
    }

    public virtual async Task LockAsync(Guid id, int seconds)
    {
        await RequestAsync(nameof(LockAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(int), seconds }
        });
    }

    public virtual async Task UnLockAsync(Guid id)
    {
        await RequestAsync(nameof(UnLockAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
