// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using LINGYUN.Abp.Identity;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace LINGYUN.Abp.Identity;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IIdentitySessionAppService), typeof(IdentitySessionClientProxy))]
public partial class IdentitySessionClientProxy : ClientProxyBase<IIdentitySessionAppService>, IIdentitySessionAppService
{
    public virtual async Task<PagedResultDto<IdentitySessionDto>> GetSessionsAsync(GetUserSessionsInput input)
    {
        return await RequestAsync<PagedResultDto<IdentitySessionDto>>(nameof(GetSessionsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetUserSessionsInput), input }
        });
    }

    public virtual async Task RevokeSessionAsync(string sessionId)
    {
        await RequestAsync(nameof(RevokeSessionAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), sessionId }
        });
    }
}
