// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using LINGYUN.Abp.BlobManagement;
using LINGYUN.Abp.BlobManagement.Dtos;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace LINGYUN.Abp.BlobManagement.Dtos;

public class BlobDto : ExtensibleAuditedEntityDto<Guid>
{
    public string Name { get; set; }

    public string Path { get; set; }

    public BlobType Type { get; set; }

    public string ContentType { get; set; }

    public long Size { get; set; }

    public DateTime? ExpirationTime { get; set; }

    public long DownloadCount { get; set; }
}
