// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using LINGYUN.Abp.OssManagement;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace LINGYUN.Abp.OssManagement;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IStaticFilesAppService), typeof(StaticFilesClientProxy))]
public partial class StaticFilesClientProxy : ClientProxyBase<IStaticFilesAppService>, IStaticFilesAppService
{
    public virtual async Task<IRemoteStreamContent> GetAsync(GetStaticFileInput input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetStaticFileInput), input }
        });
    }
}
