// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using LINGYUN.Platform.Portal;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace LINGYUN.Platform.Portal;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IEnterpriseAppService), typeof(EnterpriseClientProxy))]
public partial class EnterpriseClientProxy : ClientProxyBase<IEnterpriseAppService>, IEnterpriseAppService
{
    public virtual async Task<EnterpriseDto> CreateAsync(EnterpriseCreateDto input)
    {
        return await RequestAsync<EnterpriseDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(EnterpriseCreateDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<EnterpriseDto> GetAsync(Guid id)
    {
        return await RequestAsync<EnterpriseDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<EnterpriseDto>> GetListAsync(EnterpriseGetListInput input)
    {
        return await RequestAsync<PagedResultDto<EnterpriseDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(EnterpriseGetListInput), input }
        });
    }

    public virtual async Task<EnterpriseDto> UpdateAsync(Guid id, EnterpriseUpdateDto input)
    {
        return await RequestAsync<EnterpriseDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(EnterpriseUpdateDto), input }
        });
    }
}
