version: '3.4'

services:
  auth-server:
    build:
      context: .
      dockerfile: aspnet-core/services/LINGYUN.Abp.MicroService.AuthServer/Dockerfile
    volumes:
      - ./deploy/framework/auth-server/logs:/app/Logs
      - ./deploy/framework/auth-server/modules:/app/Modules
    restart: always

  identity-service:
    build:
      context: .
      dockerfile: aspnet-core/services/LINGYUN.Abp.MicroService.IdentityService/Dockerfile
    volumes:
      - ./deploy/framework/identity-service/logs:/app/Logs
      - ./deploy/framework/identity-service/modules:/app/Modules
    restart: always
    depends_on:
      - auth-server

  admin-service:
    build:
      context: .
      dockerfile: aspnet-core/services/LINGYUN.Abp.MicroService.AdminService/Dockerfile
    volumes:
      - ./deploy/framework/admin-service/logs:/app/Logs
      - ./deploy/framework/admin-service/modules:/app/Modules
    restart: always
    depends_on:
      - auth-server

  localization-service:
    build:
      context: .
      dockerfile: aspnet-core/services/LINGYUN.Abp.MicroService.LocalizationService/Dockerfile
    volumes:
      - ./deploy/framework/localization-service/logs:/app/Logs
      - ./deploy/framework/localization-service/modules:/app/Modules
    restart: always
    depends_on:
      - auth-server

  platform-service:
    build:
      context: .
      dockerfile: aspnet-core/services/LINGYUN.Abp.MicroService.PlatformService/Dockerfile
    volumes:
      - ./deploy/framework/platform-service/logs:/app/Logs
      - ./deploy/framework/platform-service/modules:/app/Modules
      - ./deploy/framework/platform-service/blobs:/app/file-blob-storing
    restart: always
    depends_on:
      - auth-server

  message-service:
    build:
      context: .
      dockerfile: aspnet-core/services/LINGYUN.Abp.MicroService.MessageService/Dockerfile
    volumes:
      - ./deploy/framework/message-service/logs:/app/Logs
      - ./deploy/framework/message-service/modules:/app/Modules
    restart: always
    depends_on:
      - auth-server

  task-service:
    build:
      context: .
      dockerfile: aspnet-core/services/LINGYUN.Abp.MicroService.TaskService/Dockerfile
    volumes:
      - ./deploy/framework/task-service/logs:/app/Logs
      - ./deploy/framework/task-service/modules:/app/Modules
    restart: always
    depends_on:
      - auth-server

  webhook-service:
    build:
      context: .
      dockerfile: aspnet-core/services/LINGYUN.Abp.MicroService.WebhookService/Dockerfile
    volumes:
      - ./deploy/framework/webhook-service/logs:/app/Logs
      - ./deploy/framework/webhook-service/modules:/app/Modules
    restart: always
    depends_on:
      - auth-server

  workflow-service:
    build:
      context: .
      dockerfile: aspnet-core/services/LINGYUN.Abp.MicroService.WorkflowService/Dockerfile
    volumes:
      - ./deploy/framework/workflow-service/logs:/app/Logs
      - ./deploy/framework/workflow-service/modules:/app/Modules
    restart: always
    depends_on:
      - auth-server

  wechat-service:
    build:
      context: .
      dockerfile: aspnet-core/services/LINGYUN.Abp.MicroService.WeChatService/Dockerfile
    volumes:
      - ./deploy/framework/wechat-service/logs:/app/Logs
      - ./deploy/framework/wechat-service/modules:/app/Modules
    restart: always
    depends_on:
      - auth-server

  internal-apigateway:
    build:
      context: .
      dockerfile: gateways/internal/LINGYUN.MicroService.Internal.ApiGateway/src/LINGYUN.MicroService.Internal.Gateway/Dockerfile
    volumes:
      - ./deploy/framework/internal-apigateway/logs:/app/Logs
      - ./deploy/framework/internal-apigateway/modules:/app/Modules
    restart: always

  # ui:
  #   build:
  #     context: ./apps/vue
  #   restart: always
