version: '3.4'

services:
  sts-server:
    environment:
      - App__SelfUrl=http://127.0.0.1:44385/
      - App__CorsOrigins=http://127.0.0.1:9527,http://127.0.0.1:9528,http://127.0.0.1:40000,http://127.0.0.1:30000
      - App__TrackingEntitiesChanged=true
      - ConnectionStrings__Default=Server=127.0.0.1;Database=IdentityServer;User Id=root;Password=123456
      - ConnectionStrings__AbpIdentity=Server=127.0.0.1;Database=IdentityServer;User Id=root;Password=123456
      - ConnectionStrings__AbpIdentityServer=Server=127.0.0.1;Database=IdentityServer;User Id=root;Password=123456
      - ConnectionStrings__AbpAuditLogging=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpTenantManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpSettingManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpPermissionManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpFeatureManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - Certificates__CerPath=./idsrv4.pfx
      - Certificates__Password=csfvw2-2r0ff41
      - Encryption__PassPhrase=s46c5q55nxpeS8Ra
      - Encryption__InitVector=s83ng0abvd02js84
      - Encryption__Salt=sf&5)s3#
      - CAP__EventBus__DefaultGroup=AuthServer
      - CAP__EventBus__Version=v1
      - CAP__EventBus__FailedRetryInterval=300
      - CAP__EventBus__FailedRetryCount=10
      - CAP__RabbitMQ__HostName=127.0.0.1
      - CAP__RabbitMQ__Port=5672
      - CAP__RabbitMQ__UserName=admin
      - CAP__RabbitMQ__Password=123456
      - CAP__RabbitMQ__ExchangeName=LINGYUN.Abp.Application
      - CAP__RabbitMQ__VirtualHost=/
      - Redis__Configuration=127.0.0.1,defaultDatabase=10
      - Redis__InstanceName=LINGYUN.Abp.Application
      - AuthServer__Authority=http://127.0.0.1:44385/
      - AuthServer__ApiName=lingyun-abp-application
      - IdentityServer__Clients__AuthManagement__ClientId=auth-management
      - IdentityServer__Clients__AuthManagement__RootUrl=http://127.0.0.1:9527/
      - IdentityServer__Clients__AuthVueAdmin__ClientId=vue-admin-element
      - IdentityServer__Clients__AuthApiGateway__ClientId=ApigatewayHostClient
      - IdentityServer__Clients__AuthApiGatewayAdmin__ClientId=apigateway-admin-client

  sts-api:
    environment:
      - App__TrackingEntitiesChanged=true
      - ConnectionStrings__Default=Server=127.0.0.1;Database=IdentityServer;User Id=root;Password=123456
      - ConnectionStrings__AbpIdentity=Server=127.0.0.1;Database=IdentityServer;User Id=root;Password=123456
      - ConnectionStrings__AbpIdentityServer=Server=127.0.0.1;Database=IdentityServer;User Id=root;Password=123456
      - ConnectionStrings__AbpAuditLogging=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpTenantManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpSettingManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpPermissionManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpFeatureManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - Encryption__PassPhrase=s46c5q55nxpeS8Ra
      - Encryption__InitVector=s83ng0abvd02js84
      - Encryption__Salt=sf&5)s3#
      - CAP__EventBus__DefaultGroup=IdentityServer4Admin
      - CAP__EventBus__Version=v1
      - CAP__EventBus__FailedRetryInterval=300
      - CAP__EventBus__FailedRetryCount=10
      - CAP__RabbitMQ__HostName=127.0.0.1
      - CAP__RabbitMQ__Port=5672
      - CAP__RabbitMQ__UserName=admin
      - CAP__RabbitMQ__Password=123456
      - CAP__RabbitMQ__ExchangeName=LINGYUN.Abp.Application
      - CAP__RabbitMQ__VirtualHost=/
      - Redis__Configuration=127.0.0.1,defaultDatabase=10
      - Redis__InstanceName=LINGYUN.Abp.Application
      - AuthServer__Authority=http://127.0.0.1:44385/
      - AuthServer__ApiName=lingyun-abp-application

  admin-api:
    environment:
      - App__TrackingEntitiesChanged=true
      - ConnectionStrings__Default=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpIdentity=Server=127.0.0.1;Database=IdentityServer;User Id=root;Password=123456
      - ConnectionStrings__AbpIdentityServer=Server=127.0.0.1;Database=IdentityServer;User Id=root;Password=123456
      - ConnectionStrings__AbpAuditLogging=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpTenantManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpSettingManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpPermissionManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - Encryption__PassPhrase=s46c5q55nxpeS8Ra
      - Encryption__InitVector=s83ng0abvd02js84
      - Encryption__Salt=sf&5)s3#
      - CAP__EventBus__DefaultGroup=BackendAdmin
      - CAP__EventBus__Version=v1
      - CAP__EventBus__FailedRetryInterval=300
      - CAP__EventBus__FailedRetryCount=10
      - CAP__RabbitMQ__HostName=127.0.0.1
      - CAP__RabbitMQ__Port=5672
      - CAP__RabbitMQ__UserName=admin
      - CAP__RabbitMQ__Password=123456
      - CAP__RabbitMQ__ExchangeName=LINGYUN.Abp.Application
      - CAP__RabbitMQ__VirtualHost=/
      - Redis__Configuration=127.0.0.1,defaultDatabase=10
      - Redis__InstanceName=LINGYUN.Abp.Application
      - AuthServer__Authority=http://127.0.0.1:44385/
      - AuthServer__ApiName=lingyun-abp-application

  localization-api:
    environment:
      - App__TrackingEntitiesChanged=true
      - ConnectionStrings__Default=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpLocalizationManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpAuditLogging=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpTenantManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpSettingManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpPermissionManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - Encryption__PassPhrase=s46c5q55nxpeS8Ra
      - Encryption__InitVector=s83ng0abvd02js84
      - Encryption__Salt=sf&5)s3#
      - CAP__EventBus__DefaultGroup=Localization-Management
      - CAP__EventBus__Version=v1
      - CAP__EventBus__FailedRetryInterval=300
      - CAP__EventBus__FailedRetryCount=10
      - CAP__RabbitMQ__HostName=127.0.0.1
      - CAP__RabbitMQ__Port=5672
      - CAP__RabbitMQ__UserName=admin
      - CAP__RabbitMQ__Password=123456
      - CAP__RabbitMQ__ExchangeName=LINGYUN.Abp.Application
      - CAP__RabbitMQ__VirtualHost=/
      - Redis__Configuration=127.0.0.1,defaultDatabase=10
      - Redis__InstanceName=LINGYUN.Abp.Application
      - AuthServer__Authority=http://127.0.0.1:44385/
      - AuthServer__ApiName=lingyun-abp-application

  platform-api:
    environment:
      - App__TrackingEntitiesChanged=true
      - ConnectionStrings__Default=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AppPlatform=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpAuditLogging=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpTenantManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpSettingManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpPermissionManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - RemoteServices__AbpIdentity__BaseUrl=http://127.0.0.1:30015/
      - RemoteServices__AbpIdentity__IdentityClient=InternalServiceClient
      - IdentityClients__InternalServiceClient__Authority=http://127.0.0.1:44385/
      - IdentityClients__InternalServiceClient__RequireHttps=false
      - IdentityClients__InternalServiceClient__GrantType=client_credentials
      - IdentityClients__InternalServiceClient__Scope=lingyun-abp-application
      - IdentityClients__InternalServiceClient__ClientId=internal-service-client
      - IdentityClients__InternalServiceClient__ClientSecret=1q2w3e*
      - Encryption__PassPhrase=s46c5q55nxpeS8Ra
      - Encryption__InitVector=s83ng0abvd02js84
      - Encryption__Salt=sf&5)s3#
      - Features__Validation__Redis__Configuration=127.0.0.1,defaultDatabase=11
      - Features__Validation__Redis__InstanceName=LINGYUN.Abp.Application
      - CAP__EventBus__DefaultGroup=Platform
      - CAP__EventBus__Version=v1
      - CAP__EventBus__FailedRetryInterval=300
      - CAP__EventBus__FailedRetryCount=10
      - CAP__RabbitMQ__HostName=127.0.0.1
      - CAP__RabbitMQ__Port=5672
      - CAP__RabbitMQ__UserName=admin
      - CAP__RabbitMQ__Password=123456
      - CAP__RabbitMQ__ExchangeName=LINGYUN.Abp.Application
      - CAP__RabbitMQ__VirtualHost=/
      - Redis__Configuration=127.0.0.1,defaultDatabase=10
      - Redis__InstanceName=LINGYUN.Abp.Application
      - AuthServer__Authority=http://127.0.0.1:44385/
      - AuthServer__ApiName=lingyun-abp-application

  messages-api:
    environment:
      - App__CorsOrigins=http://127.0.0.1:40000,http://127.0.0.1:30000
      - App__TrackingEntitiesChanged=true
      - ConnectionStrings__Default=Server=127.0.0.1;Database=Messages;User Id=root;Password=123456
      - ConnectionStrings__MessageService=Server=127.0.0.1;Database=Messages;User Id=root;Password=123456
      - ConnectionStrings__AbpTenantManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpSettingManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - ConnectionStrings__AbpPermissionManagement=Server=127.0.0.1;Database=Platform;User Id=root;Password=123456
      - Encryption__PassPhrase=s46c5q55nxpeS8Ra
      - Encryption__InitVector=s83ng0abvd02js84
      - Encryption__Salt=sf&5)s3#
      - CAP__EventBus__DefaultGroup=MessageService
      - CAP__EventBus__Version=v1
      - CAP__EventBus__FailedRetryInterval=300
      - CAP__EventBus__FailedRetryCount=10
      - CAP__RabbitMQ__HostName=127.0.0.1
      - CAP__RabbitMQ__Port=5672
      - CAP__RabbitMQ__UserName=admin
      - CAP__RabbitMQ__Password=123456
      - CAP__RabbitMQ__ExchangeName=LINGYUN.Abp.Application
      - CAP__RabbitMQ__VirtualHost=/
      - Redis__Configuration=127.0.0.1,defaultDatabase=10
      - Redis__InstanceName=LINGYUN.Abp.Application
      - AuthServer__Authority=http://127.0.0.1:44385/
      - AuthServer__ApiName=lingyun-abp-application
      - Hangfire__MySql__Connection=Server=127.0.0.1;Database=Messages;User Id=root;Password=123456;Allow User Variables=true
      - Hangfire__Dashboard__WhiteList=127.0.0.1
      - Notifications__WeChat__WeApp__DefaultWeAppState=formal

  task-api:
    environment:
      - App__TrackingEntitiesChanged=true
      - ConnectionStrings__Default=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - ConnectionStrings__TaskManagement=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - ConnectionStrings__AbpFeatureManagement=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - ConnectionStrings__AbpPermissionManagement=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - ConnectionStrings__AbpLocalizationManagement=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - ConnectionStrings__AbpSettingManagement=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - ConnectionStrings__AbpSaas=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - Encryption__PassPhrase=s46c5q55nxpeS8Ra
      - Encryption__InitVector=s83ng0abvd02js84
      - Encryption__Salt=sf&5)s3#
      - CAP__EventBus__DefaultGroup=TaskManagement
      - CAP__EventBus__Version=v1
      - CAP__EventBus__FailedRetryInterval=300
      - CAP__EventBus__FailedRetryCount=10
      - CAP__RabbitMQ__HostName=127.0.0.1
      - CAP__RabbitMQ__Port=5672
      - CAP__RabbitMQ__UserName=admin
      - CAP__RabbitMQ__Password=123456
      - CAP__RabbitMQ__ExchangeName=LINGYUN.Abp.Application
      - CAP__RabbitMQ__VirtualHost=/
      - Redis__Configuration=127.0.0.1,defaultDatabase=10
      - Redis__InstanceName=LINGYUN.Abp.Application
      - AuthServer__Authority=http://127.0.0.1:44385/
      - AuthServer__ApiName=lingyun-abp-application

  webhook-api:
    environment:
      - App__TrackingEntitiesChanged=true
      - ConnectionStrings__Default=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - ConnectionStrings__WebhooksManagement=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - ConnectionStrings__TaskManagement=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - ConnectionStrings__AbpSaas=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - ConnectionStrings__AbpFeatureManagement=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - ConnectionStrings__AbpPermissionManagement=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - ConnectionStrings__AbpSettingManagement=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - Encryption__PassPhrase=s46c5q55nxpeS8Ra
      - Encryption__InitVector=s83ng0abvd02js84
      - Encryption__Salt=sf&5)s3#
      - CAP__EventBus__DefaultGroup=WebhooksManagement
      - CAP__EventBus__Version=v1
      - CAP__EventBus__FailedRetryInterval=300
      - CAP__EventBus__FailedRetryCount=10
      - CAP__RabbitMQ__HostName=127.0.0.1
      - CAP__RabbitMQ__Port=5672
      - CAP__RabbitMQ__UserName=admin
      - CAP__RabbitMQ__Password=123456
      - CAP__RabbitMQ__ExchangeName=LINGYUN.Abp.Application
      - CAP__RabbitMQ__VirtualHost=/
      - Redis__Configuration=127.0.0.1,defaultDatabase=10
      - Redis__InstanceName=LINGYUN.Abp.Application
      - AuthServer__Authority=http://127.0.0.1:44385/
      - AuthServer__ApiName=lingyun-abp-application

  workflow-api:
    environment:
      - App__TrackingEntitiesChanged=true
      - ConnectionStrings__Default=Server=127.0.0.1;Database=Workflow;User Id=root;Password=123456,
      - ConnectionStrings__Workflow=Server=127.0.0.1;Database=Workflow;User Id=root;Password=123456,
      - ConnectionStrings__WorkflowManagement=Server=127.0.0.1;Database=Workflow;User Id=root;Password=123456,
      - ConnectionStrings__AbpWorkflowCore=Server=127.0.0.1;Database=Workflow;User Id=root;Password=123456,
      - ConnectionStrings__AbpFeatureManagement=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - ConnectionStrings__AbpPermissionManagement=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - ConnectionStrings__AbpLocalizationManagement=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - ConnectionStrings__AbpSettingManagement=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - ConnectionStrings__AbpSaas=Server=127.0.0.1;Database=Platform-v70;User Id=root;Password=123456,
      - Encryption__PassPhrase=s46c5q55nxpeS8Ra
      - Encryption__InitVector=s83ng0abvd02js84
      - Encryption__Salt=sf&5)s3#
      - CAP__EventBus__DefaultGroup=Workflow
      - CAP__EventBus__Version=v1
      - CAP__EventBus__FailedRetryInterval=300
      - CAP__EventBus__FailedRetryCount=10
      - CAP__RabbitMQ__HostName=127.0.0.1
      - CAP__RabbitMQ__Port=5672
      - CAP__RabbitMQ__UserName=admin
      - CAP__RabbitMQ__Password=123456
      - CAP__RabbitMQ__ExchangeName=LINGYUN.Abp.Application
      - CAP__RabbitMQ__VirtualHost=/
      - Redis__Configuration=127.0.0.1,defaultDatabase=10
      - Redis__InstanceName=LINGYUN.Abp.Application
      - AuthServer__Authority=http://127.0.0.1:44385/
      - AuthServer__ApiName=lingyun-abp-application

  internal-apigateway:
    environment:
      - App__TrackingEntitiesChanged=true
      - Encryption__PassPhrase=s46c5q55nxpeS8Ra
      - Encryption__InitVector=s83ng0abvd02js84
      - Encryption__Salt=sf&5)s3#
      - Redis__Configuration=127.0.0.1,defaultDatabase=10
      - Redis__InstanceName=LINGYUN.Abp.Application
      - AuthServer__Authority=http://127.0.0.1:44385/
      - AuthServer__ApiName=lingyun-abp-application
