<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\..\configureawait.props" />
	<Import Project="..\..\..\..\common.props" />

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>LINGYUN.Abp.ElsaNext.BlobStoring</AssemblyName>
		<PackageId>LINGYUN.Abp.ElsaNext.BlobStoring</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="LINGYUN\Abp\ElsaNext\BlobStoring\Localization\**\*.json" />
		<EmbeddedResource Include="LINGYUN\Abp\ElsaNext\BlobStoring\Localization\**\*.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.BlobStoring" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LINGYUN.Abp.ElsaNext\LINGYUN.Abp.ElsaNext.csproj" />
	</ItemGroup>

</Project>
