// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using LINGYUN.Abp.BlobManagement.Dtos;
using LINGYUN.Abp.BlobManagement.Integration;
using LINGYUN.Abp.BlobManagement.Integration.Dtos;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace LINGYUN.Abp.BlobManagement.Integration;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IBlobIntegrationService), typeof(BlobIntegrationClientProxy))]
[IntegrationService]
public partial class BlobIntegrationClientProxy : ClientProxyBase<IBlobIntegrationService>, IBlobIntegrationService
{
    public virtual async Task<BlobDto> CreateAsync(BlobFileCreateIntegrationDto input)
    {
        return await RequestAsync<BlobDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BlobFileCreateIntegrationDto), input }
        });
    }

    public virtual async Task DeleteAsync(BlobFileGetByNameIntegrationDto input)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BlobFileGetByNameIntegrationDto), input }
        });
    }

    public virtual async Task<bool> ExistsAsync(BlobFileGetByNameIntegrationDto input)
    {
        return await RequestAsync<bool>(nameof(ExistsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BlobFileGetByNameIntegrationDto), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetContentAsync(BlobFileGetByNameIntegrationDto input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetContentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BlobFileGetByNameIntegrationDto), input }
        });
    }
}
