// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using LINGYUN.Abp.WebhooksManagement;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace LINGYUN.Abp.WebhooksManagement;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IWebhookPublishAppService), typeof(WebhookPublishClientProxy))]
public partial class WebhookPublishClientProxy : ClientProxyBase<IWebhookPublishAppService>, IWebhookPublishAppService
{
    public virtual async Task PublishAsync(WebhookPublishInput input)
    {
        await RequestAsync(nameof(PublishAsync), new ClientProxyRequestTypeValue
        {
            { typeof(WebhookPublishInput), input }
        });
    }
}
