<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\..\configureawait.props" />
	<Import Project="..\..\..\..\common.props" />

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>LINGYUN.Abp.OpenObserve</AssemblyName>
		<PackageId>LINGYUN.Abp.OpenObserve</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.Json" />
		<PackageReference Include="Microsoft.Extensions.Http" />
	</ItemGroup>

</Project>
