// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using LINGYUN.Platform.Datas;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace LINGYUN.Platform.Datas;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IGlobalDataAppService), typeof(GlobalDataClientProxy))]
public partial class GlobalDataClientProxy : ClientProxyBase<IGlobalDataAppService>, IGlobalDataAppService
{
    public virtual async Task<DataDto> GetByNameAsync(string name)
    {
        return await RequestAsync<DataDto>(nameof(GetByNameAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }

    public virtual async Task<DataDto> GetAsync(Guid id)
    {
        return await RequestAsync<DataDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListResultDto<DataDto>> GetAllAsync()
    {
        return await RequestAsync<ListResultDto<DataDto>>(nameof(GetAllAsync));
    }
}
