<Project Sdk="Microsoft.NET.Sdk.Razor">

	<Import Project="..\..\..\..\configureawait.props" />
	<Import Project="..\..\..\..\common.props" />

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyName>LINGYUN.Abp.ElsaNext.Studio.Labels.Blazor</AssemblyName>
		<PackageId>LINGYUN.Abp.ElsaNext.Studio.Labels.Blazor</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="Localization\Resources\LabelsBlazor\*.json" />
		<EmbeddedResource Include="Localization\Resources\LabelsBlazor\*.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Elsa.Studio.Labels" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LINGYUN.Abp.ElsaNext.Labels\LINGYUN.Abp.ElsaNext.Labels.csproj" />
		<ProjectReference Include="..\LINGYUN.Abp.ElsaNext.Studio.Blazor\LINGYUN.Abp.ElsaNext.Studio.Blazor.csproj" />
	</ItemGroup>

</Project>
