// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using LINGYUN.Abp.Notifications.Definitions.Groups;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace LINGYUN.Abp.Notifications.Definitions.Groups;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(INotificationGroupDefinitionAppService), typeof(NotificationGroupDefinitionClientProxy))]
public partial class NotificationGroupDefinitionClientProxy : ClientProxyBase<INotificationGroupDefinitionAppService>, INotificationGroupDefinitionAppService
{
    public virtual async Task<NotificationGroupDefinitionDto> CreateAsync(NotificationGroupDefinitionCreateDto input)
    {
        return await RequestAsync<NotificationGroupDefinitionDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(NotificationGroupDefinitionCreateDto), input }
        });
    }

    public virtual async Task DeleteAsync(string name)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }

    public virtual async Task<NotificationGroupDefinitionDto> GetAsync(string name)
    {
        return await RequestAsync<NotificationGroupDefinitionDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }

    public virtual async Task<ListResultDto<NotificationGroupDefinitionDto>> GetListAsync(NotificationGroupDefinitionGetListInput input)
    {
        return await RequestAsync<ListResultDto<NotificationGroupDefinitionDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(NotificationGroupDefinitionGetListInput), input }
        });
    }

    public virtual async Task<NotificationGroupDefinitionDto> UpdateAsync(string name, NotificationGroupDefinitionUpdateDto input)
    {
        return await RequestAsync<NotificationGroupDefinitionDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name },
            { typeof(NotificationGroupDefinitionUpdateDto), input }
        });
    }
}
