// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using LINGYUN.Abp.Account;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace LINGYUN.Abp.Account;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IMyClaimAppService), typeof(MyClaimClientProxy))]
public partial class MyClaimClientProxy : ClientProxyBase<IMyClaimAppService>, IMyClaimAppService
{
    public virtual async Task ChangeAvatarAsync(ChangeAvatarInput input)
    {
        await RequestAsync(nameof(ChangeAvatarAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ChangeAvatarInput), input }
        });
    }

    public virtual async Task<GetUserClaimStateDto> GetStateAsync(string claimType)
    {
        return await RequestAsync<GetUserClaimStateDto>(nameof(GetStateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), claimType }
        });
    }

    public virtual async Task ResetAsync(string claimType)
    {
        await RequestAsync(nameof(ResetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), claimType }
        });
    }
}
