<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\..\configureawait.props" />
	<Import Project="..\..\..\..\common.props" />

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>LINGYUN.Abp.ElsaNext.Server</AssemblyName>
		<PackageId>LINGYUN.Abp.ElsaNext.Server</PackageId>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<None Remove="LINGYUN\Abp\ElsaNext\Server\Localization\Resources\*.json" />
		<EmbeddedResource Include="LINGYUN\Abp\ElsaNext\Server\Localization\Resources\*.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Elsa.Api.Common" VersionOverride="$(ElsaNextPackageVersion)" />
		<PackageReference Include="Elsa.Dashboard.Api" VersionOverride="$(ElsaNextPackageVersion)" />
		<PackageReference Include="Elsa.Expressions.CSharp" VersionOverride="$(ElsaNextPackageVersion)" />
		<PackageReference Include="Elsa.Expressions.JavaScript" VersionOverride="$(ElsaNextPackageVersion)" />
		<PackageReference Include="Elsa.Expressions.Liquid" VersionOverride="$(ElsaNextPackageVersion)" />
		<PackageReference Include="Elsa.Http" VersionOverride="$(ElsaNextPackageVersion)" />
		<PackageReference Include="Elsa.Scheduling" VersionOverride="$(ElsaNextPackageVersion)" />
		<PackageReference Include="Elsa.Workflows.Api" VersionOverride="$(ElsaNextPackageVersion)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LINGYUN.Abp.ElsaNext\LINGYUN.Abp.ElsaNext.csproj" />
	</ItemGroup>

</Project>
