<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace />
		<IsPackable>false</IsPackable>
		<Platforms>AnyCPU</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Moq.AutoMock" />
		<PackageReference Include="Serilog.Sinks.InMemory" />
		<PackageReference Include="Serilog.Extensions.Logging" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\framework\logging\LINGYUN.Abp.Logging\LINGYUN.Abp.Logging.csproj" />
		<ProjectReference Include="..\..\framework\logging\LINGYUN.Abp.Serilog.Enrichers.UniqueId\LINGYUN.Abp.Serilog.Enrichers.UniqueId.csproj" />
		<ProjectReference Include="..\LINGYUN.Abp.TestBase\LINGYUN.Abp.TestsBase.csproj" />
	</ItemGroup>
</Project>
