<Project Sdk="Microsoft.NET.Sdk.Razor">

	<Import Project="..\..\..\..\configureawait.props" />
	<Import Project="..\..\..\..\common.props" />

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>LINGYUN.Abp.ElsaNext.Secrets.Blazor</AssemblyName>
		<PackageId>LINGYUN.Abp.ElsaNext.Secrets.Blazor</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="Localization\Resources\SecretsBlazor\*.json" />
		<EmbeddedResource Include="Localization\Resources\SecretsBlazor\*.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Elsa.Studio.Secrets" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LINGYUN.Abp.ElsaNext.Secrets\LINGYUN.Abp.ElsaNext.Secrets.csproj" />
		<ProjectReference Include="..\LINGYUN.Abp.ElsaNext.Studio.Blazor\LINGYUN.Abp.ElsaNext.Studio.Blazor.csproj" />
	</ItemGroup>

</Project>
