// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using LINGYUN.Abp.Auditing.Logging;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace LINGYUN.Abp.Auditing.Logging;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ILogAppService), typeof(LogClientProxy))]
public partial class LogClientProxy : ClientProxyBase<ILogAppService>, ILogAppService
{
    public virtual async Task<LogDto> GetAsync(string id)
    {
        return await RequestAsync<LogDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), id }
        });
    }

    public virtual async Task<PagedResultDto<LogDto>> GetListAsync(LogGetByPagedDto input)
    {
        return await RequestAsync<PagedResultDto<LogDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(LogGetByPagedDto), input }
        });
    }
}
