<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\..\configureawait.props" />
	<Import Project="..\..\..\..\common.props" />

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>LINGYUN.Abp.AspNetCore.Authentication</AssemblyName>
		<PackageId>LINGYUN.Abp.AspNetCore.Authentication</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Volo.Abp.AspNetCore" />
		<PackageReference Include="Volo.Abp.Security" />
		<PackageReference Include="Duende.IdentityModel" />
		<!-- 对齐整体Microsoft.IdentityModel.Tokens版本 -->
		<PackageReference Include="Microsoft.IdentityModel.Tokens" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
		<PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" />
	</ItemGroup>

</Project>