<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\..\configureawait.props" />
	<Import Project="..\..\..\..\common.props" />

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1;net8.0;net9.0;net10.0</TargetFrameworks>
		<AssemblyName>LINGYUN.Abp.Dingtalk.Messages</AssemblyName>
		<PackageId>LINGYUN.Abp.Dingtalk.Messages</PackageId>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<Description>钉钉消息通知模块集成</Description>
		<Nullable>enable</Nullable>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\LINGYUN.Abp.Dingtalk\LINGYUN.Abp.Dingtalk.csproj" />
	</ItemGroup>

</Project>
