// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using LINGYUN.Abp.WebhooksManagement.Definitions;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace LINGYUN.Abp.WebhooksManagement.Definitions;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IWebhookGroupDefinitionAppService), typeof(WebhookGroupDefinitionClientProxy))]
public partial class WebhookGroupDefinitionClientProxy : ClientProxyBase<IWebhookGroupDefinitionAppService>, IWebhookGroupDefinitionAppService
{
    public virtual async Task<WebhookGroupDefinitionDto> CreateAsync(WebhookGroupDefinitionCreateDto input)
    {
        return await RequestAsync<WebhookGroupDefinitionDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(WebhookGroupDefinitionCreateDto), input }
        });
    }

    public virtual async Task DeleteAsync(string name)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }

    public virtual async Task<WebhookGroupDefinitionDto> GetAsync(string name)
    {
        return await RequestAsync<WebhookGroupDefinitionDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }

    public virtual async Task<ListResultDto<WebhookGroupDefinitionDto>> GetListAsync(WebhookGroupDefinitionGetListInput input)
    {
        return await RequestAsync<ListResultDto<WebhookGroupDefinitionDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(WebhookGroupDefinitionGetListInput), input }
        });
    }

    public virtual async Task<WebhookGroupDefinitionDto> UpdateAsync(string name, WebhookGroupDefinitionUpdateDto input)
    {
        return await RequestAsync<WebhookGroupDefinitionDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name },
            { typeof(WebhookGroupDefinitionUpdateDto), input }
        });
    }
}
