<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\..\..\common.secrets.props" />

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Serilog.Extensions.Logging" />
		<PackageReference Include="Serilog.Sinks.File" />
		<PackageReference Include="Serilog.Sinks.Console" />
		<PackageReference Include="Volo.Abp.Autofac" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="Logs\**" />
		<Content Remove="Logs\**" />
		<EmbeddedResource Remove="Logs\**" />
		<None Remove="Logs\**" />
		<None Remove="appsettings.json" />
		<Content Include="appsettings.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LINGYUN.Abp.MicroService.AllInOne.EntityFrameworkCore.PostgreSql\LINGYUN.Abp.MicroService.AllInOne.EntityFrameworkCore.PostgreSql.csproj" />
		<ProjectReference Include="..\LINGYUN.Abp.MicroService.AllInOne.EntityFrameworkCore.MySql\LINGYUN.Abp.MicroService.AllInOne.EntityFrameworkCore.MySql.csproj" />
		<ProjectReference Include="..\LINGYUN.Abp.MicroService.AllInOne.EntityFrameworkCore.SqlServer\LINGYUN.Abp.MicroService.AllInOne.EntityFrameworkCore.SqlServer.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="appsettings.MySql.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="appsettings.PostgreSql.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="appsettings.SqlServer.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Properties\launchSettings.json">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	    <CopyToPublishDirectory>Never</CopyToPublishDirectory>
	  </None>
	</ItemGroup>

</Project>
