// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using LINGYUN.Abp.BlobManagement.Integration.Dtos;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace LINGYUN.Abp.BlobManagement.Integration.Dtos;

public class BlobFileGetByNameIntegrationDto
{
    public string ContainerName { get; set; }

    public string BlobName { get; set; }
}
