// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using LINGYUN.Abp.BlobManagement;
using LINGYUN.Abp.BlobManagement.Dtos;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace LINGYUN.Abp.BlobManagement;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IBlobContainerAppService), typeof(BlobContainerClientProxy))]
public partial class BlobContainerClientProxy : ClientProxyBase<IBlobContainerAppService>, IBlobContainerAppService
{
    public virtual async Task<BlobContainerDto> CreateAsync(BlobContainerCreateDto input)
    {
        return await RequestAsync<BlobContainerDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BlobContainerCreateDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<BlobContainerDto> GetAsync(Guid id)
    {
        return await RequestAsync<BlobContainerDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<BlobContainerDto>> GetListAsync(BlobContainerGetPagedListInput input)
    {
        return await RequestAsync<PagedResultDto<BlobContainerDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BlobContainerGetPagedListInput), input }
        });
    }
}
