// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using LINGYUN.Abp.BlobManagement;
using LINGYUN.Abp.BlobManagement.Dtos;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace LINGYUN.Abp.BlobManagement;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IBlobAppService), typeof(BlobClientProxy))]
public partial class BlobClientProxy : ClientProxyBase<IBlobAppService>, IBlobAppService
{
    public virtual async Task<BlobDto> CreateFileAsync(BlobFileCreateDto input)
    {
        return await RequestAsync<BlobDto>(nameof(CreateFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BlobFileCreateDto), input }
        });
    }

    public virtual async Task CreateChunkFileAsync(BlobFileChunkCreateDto input)
    {
        await RequestAsync(nameof(CreateChunkFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BlobFileChunkCreateDto), input }
        });
    }

    public virtual async Task<BlobDto> CreateFolderAsync(BlobFolderCreateDto input)
    {
        return await RequestAsync<BlobDto>(nameof(CreateFolderAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BlobFolderCreateDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetContentAsync(Guid id)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetContentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetContentByNameAsync(BlobDownloadByNameInput input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetContentByNameAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BlobDownloadByNameInput), input }
        });
    }

    public virtual async Task<BlobDto> GetAsync(Guid id)
    {
        return await RequestAsync<BlobDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<BlobDto>> GetListAsync(BlobGetPagedListInput input)
    {
        return await RequestAsync<PagedResultDto<BlobDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BlobGetPagedListInput), input }
        });
    }
}
