// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using LINGYUN.Abp.BlobManagement;
using LINGYUN.Abp.BlobManagement.Dtos;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Content;

// ReSharper disable once CheckNamespace
namespace LINGYUN.Abp.BlobManagement;

public interface IBlobAppService : IApplicationService
{
    Task<BlobDto> CreateFileAsync(BlobFileCreateDto input);

    Task CreateChunkFileAsync(BlobFileChunkCreateDto input);

    Task<BlobDto> CreateFolderAsync(BlobFolderCreateDto input);

    Task DeleteAsync(Guid id);

    Task<IRemoteStreamContent> GetContentAsync(Guid id);

    Task<IRemoteStreamContent> GetContentByNameAsync(BlobDownloadByNameInput input);

    Task<BlobDto> GetAsync(Guid id);

    Task<PagedResultDto<BlobDto>> GetListAsync(BlobGetPagedListInput input);
}
