// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using LINGYUN.Abp.BlobManagement;
using LINGYUN.Abp.BlobManagement.Dtos;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace LINGYUN.Abp.BlobManagement;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPrivateBlobAppService), typeof(PrivateBlobClientProxy))]
public partial class PrivateBlobClientProxy : ClientProxyBase<IPrivateBlobAppService>, IPrivateBlobAppService
{
    public virtual async Task<BlobDto> CreateFileAsync(BlobFileCreateWithoutContainerDto input)
    {
        return await RequestAsync<BlobDto>(nameof(CreateFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BlobFileCreateWithoutContainerDto), input }
        });
    }

    public virtual async Task CreateChunkFileAsync(BlobFileChunkCreateWithoutContainerDto input)
    {
        await RequestAsync(nameof(CreateChunkFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BlobFileChunkCreateWithoutContainerDto), input }
        });
    }

    public virtual async Task<BlobDto> CreateFolderAsync(BlobFolderCreateWithoutContainerDto input)
    {
        return await RequestAsync<BlobDto>(nameof(CreateFolderAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BlobFolderCreateWithoutContainerDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetContentAsync(Guid id)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetContentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IRemoteStreamContent> GetContentByNameAsync(string name)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(GetContentByNameAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }

    public virtual async Task<BlobDto> GetAsync(Guid id)
    {
        return await RequestAsync<BlobDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<BlobDto>> GetListAsync(BlobGetPagedListWithoutContainerInput input)
    {
        return await RequestAsync<PagedResultDto<BlobDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(BlobGetPagedListWithoutContainerInput), input }
        });
    }
}
